name: Security

on:
  push:
    branches: [ 'main', 'release-*' ]

  pull_request:
    branches: [ 'main', 'release-*' ]

jobs:
  analyze:
    uses: knative/actions/.github/workflows/security.yaml@main
